[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'fuenor/im_control.vim'
hook_add = '''
function! IMCtrl(cmd)
    let cmd = a:cmd
    if 'On' == cmd
        let res = system('ibus engine "xkb:us::eng"')
    elseif 'Off' == cmd
        let res = system('ibus engine "skk"')
    endif

    return ''
endfunction
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set background=dark

au MyAutoCmd VimEnter * nested colorscheme iceberg
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
set laststatus=2
let g:airline_powerline_fonts = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme='iceberg'
'''

